### ISSUE TITLE
Not working on deoVR

### ISSUE THREAD

**Issue by droeloe1818** [o-fl0w/stash-vr#11]
Hello,

When I open the page with DeoVR on my oculus quest 2 I get this page:

![image](https://user-images.githubusercontent.com/82944477/219678816-7e91bf00-b221-4c00-a58f-86537cd482b9.png)

**Comment by hwamil** [comment]
Yep same thing on Pico 4

**Comment by o-fl0w** [comment]
Try entering the deovr endpoint directly.
Using DeoVR browse to http://host:9666/deovr

**Comment by TheStashMaster** [comment]
I'm not sure what changed but without altering the URL the UI started working the next day.  However, not a single video will play.  Every one says "Error playing video file. Unsupported format."  Interestingly, if I copy the same file locally and play it in DeoVR it plays just fine.  Again, I suspect this has more to do with DeoVR Cardboard on Android which hasn't been updated since Oct 2021 but thought the info might be helpful.

Unrelated, you might consider an option to accept self signed certificates.  I ended up copying my root cert into the container to get around the valid TLS requirement but a bypass would be nice since this certainly would be connecting to a local docker container.

Regardless, very impressive work.  I applaud the effort and quality of project.
