### ISSUE TITLE
Scenes are visible but not playing in HereSphere player

### ISSUE THREAD

**Issue by BollywoodMaster** [o-fl0w/stash-vr#14]
Version 0.6.0.

Scenes are not playing in HereSphere player. All the preview images have gone black. Tried with DeoVR also, same issue there.

![image](https://user-images.githubusercontent.com/106441871/232687612-e1e3d5be-6775-4e9f-b3c6-23172906423e.png)

**Comment by sqdnps** [comment]
Experiencing the same issue here.

<img width="573" alt="stashvr" src="https://user-images.githubusercontent.com/79781065/234072091-93a048b6-e27d-4191-a53e-e331cfd1b9ef.png">

**Comment by o-fl0w** [comment]
Verify in your headsets browser that you can access stash directly. 

The issue you're describing is usually due to the headset not having access to Stash - because of network config/firewall rules, VPN etc.

Basically, the route to retrieve metadata, i.e. scene details etc is Headset -> Stash-VR -> Stash. The actual content is still served by stash and must be accessible directly from the headset, Headset -> Stash. 
I'm guessing your headset can reach Stash-VR and Stash-VR can reach Stash but headset can't reach Stash.

Your headset needs to be able to reach Stash.
